sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -U pip tox virtualenv codecov
script:
  - tox -e coverage
after_success:
  - codecov
matrix:
  allow_failures:
    - python: "3.3"
    - python: "nightly"
